### ISSUE TITLE
result incorrect: ValueError: cannot convert float NaN to integer

### ISSUE THREAD

**Issue by minlyzhu** [luyh20/VL-Grasp#6]
I can run the main.py, but the result is that the VL-Grasp cannot locate the object mentioned in the sentence. I 've already put two checkpoint bag under the correct path. And here is the detail(I print the bbox and mask):
~/VL-Grasp$ python main.py
WARNING:root:Failed to import ros dependencies in rigid_transforms.py
WARNING:root:autolab_core not installed as catkin package, RigidTransform ros methods will be unavailable
Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertModel: ['cls.predictions.transform.dense.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.decoder.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.dense.bias', 'cls.seq_relationship.weight', 'cls.seq_relationship.bias', 'cls.predictions.bias']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Model dim: 256
Language model dim: 768
layer 2: 1024
layer 3: 2048
layer 0: 2048
layer 1: 256
Using multi phrase loss
-> loaded visual grounding checkpoint /home/minly/VL-Grasp/checkpoint_best_r50.pth (epoch: 42)
[nan, nan, nan, nan]
[[False False False ... False False False]
 [False False False ... False False False]
 [False False False ... False False False]
 ...
 [False False False ... False False False]
 [False False False ... False False False]
 [False False False ... False False False]]
-> loaded FGC_GraspNet checkpoint /home/minly/VL-Grasp/GraspNet/checkpoint_fgc.tar (epoch: 18)
Traceback (most recent call last):
  File "main.py", line 262, in <module>
    main(args)
  File "main.py", line 250, in main
    xyz, rot, dep = grasp_net.forward(depth_ori)
  File "/home/minly/VL-Grasp/engine.py", line 356, in forward
    end_points, cloud = self.get_and_process_data(depth)
  File "/home/minly/VL-Grasp/engine.py", line 262, in get_and_process_data
    x1, y1, x2, y2 = map(int, self.bbox)
ValueError: cannot convert float NaN to integer

**Comment by zhanghr2001** [comment]
same problem for me, have you solved it?
