### ISSUE TITLE
ModuleNotFoundError: No module named 'util'

### ISSUE THREAD

**Issue by wanghq-thu** [luyh20/VL-Grasp#7]
when I run “python main.py” follow the README.
`(VL-Grasp) robot@cvailab:~/git_rep/VL-Grasp$ python main.py 
Traceback (most recent call last):
  File "main.py", line 8, in <module>
    from engine import grasp_model, vl_model
  File "/home/robot/git_rep/VL-Grasp/engine.py", line 13, in <module>
    from RoboRefIt.models import build_reftr
  File "/home/robot/git_rep/VL-Grasp/RoboRefIt/models/__init__.py", line 1, in <module>
    from .reftr_transformer import build_reftr as build_transformer_based_reftr
  File "/home/robot/git_rep/VL-Grasp/RoboRefIt/models/reftr_transformer.py", line 6, in <module>
    from util.misc import (NestedTensor, nested_tensor_from_tensor_list)
ModuleNotFoundError: No module named 'util'
`
![微信截图_20241021201628](https://github.com/user-attachments/assets/5b070cda-d297-4635-acef-b7c6c1a7f252)

**Comment by cshyb** [comment]
I'm having the same issue, can you please fix it？

**Comment by bujiebuhuo** [comment]
> I'm having the same issue, can you please fix it？

https://github.com/luyh20/VL-Grasp/engine.py There are file paths that need to be modified, you can take a look.

**Comment by wanghq-thu** [comment]
> I'm having the same issue, can you please fix it？

You can take a look `https://github.com/luyh20/VL-Grasp/engine.py` . There should be a file path in this file that needs to be modified. `sys. path. append ('/home/uyh/vlgrass/GrassNet/')` and `sys. path. append ('/home/uyh/vlgrass/RoboRefIt/')`
Change to your own file path.
